spring:
  r2dbc:
    url: r2dbc:pool:mysql://${DB_MYSQL_SIPROVISIONAS00_SIPROASPRD_SIPROASPRD_ENDPOINT}/siavpri
    username: siproasprd_WPROD
    password: ${DB_MYSQL_SIPROVISIONAS00_SIPROASPRD_SIPROASPRD_WPROD}

api:
  internal:
    base-uri: http://internal.mercadolibre.com/
    client-id: 572157570249568

logging:
  level:
    reactor:
      netty:
        http:
          client: INFO

topic:
  sap: ${BIGQUEUE_TOPIC_SAP_PRD_TOPIC_NAME}

fury-lock:
  namespace: sap-feed-prod
